### ISSUE TITLE
Migrate to React Router v6

### ISSUE THREAD

**Issue by Blaumaus** [Swetrix/swetrix-fe#18]

**Comment by Udai1931** [comment]
Hey @Alfagun74, I can work on this.

**Comment by Blaumaus** [comment]
@Udai1931 it would be great! Hit me up if you have any questions regarding the codebase

**Comment by Udai1931** [comment]
@Blaumaus, I am stuck in starting it
![image](https://user-images.githubusercontent.com/43845165/150633186-d16279b3-4c50-418d-b583-3062f85b59ac.png)
I have started swetrix-api by docker and updated the API URLin env for this project but still its in fallback UI.

**Comment by Blaumaus** [comment]
@Udai1931 yes, this is a known issue after upgrading the packages which use webpack v5.
I'll try to fix it today.

Meanwhile, what version of NodeJS do you use? It starts well on v14+, at least for me..

**Comment by Udai1931** [comment]
I am using v16 of NodeJs.

**Comment by Udai1931** [comment]
Meanwhile I will try to fix the webpack errors too.

**Comment by Blaumaus** [comment]
@Udai1931 the issue should be fixed by now. Please try to pull from the latest `main` branch and try again. Thanks!

**Comment by Udai1931** [comment]
ok @Blaumaus , Working on it.

**Comment by Blaumaus** [comment]
@Udai1931 thank you for opening a PR!
Your PR (https://github.com/Swetrix/swetrix-fe/pull/21) was accidentally merged by me a had to be reverted because it contains several flaws.
Can you please reopen this PR so I could do a review there, thanks

**Comment by Udai1931** [comment]
@Blaumaus opened PR #22 . Please tell the problems there.

**Comment by Blaumaus** [comment]
Closing this issue for now.
