### ISSUE TITLE
Default username and password?

### ISSUE THREAD

**Issue by mariushosting** [Swetrix/swetrix-fe#213]
What is the default username and password for the first connection? I try to self host it but I'm automatically redirected to the login page and I'm unable to find the signup page or find the default username and password for first connection. I have tired this according do your documentation:

EMAIL=test@test.com
PASSWORD=12345678

And I get this:
![getthis](https://user-images.githubusercontent.com/37554361/222704243-30dd5929-6088-4a6c-9dff-72f99ec59989.png)

**Comment by mariushosting** [comment]
solution found, but unable to change the default username and password once logged in.

**Comment by Blaumaus** [comment]
@mariushosting will be fixed!
