### ISSUE TITLE
Missing refresh_token cookie causing blank page

### ISSUE THREAD

**Issue by mwyywm** [Swetrix/swetrix-fe#328]
When accessing the swetrix frontend after a previous login session, I noticed that the "refresh_token" cookie was missing. As a result, the entire page appeared blank with no content displayed. I was able to resolve it myself by removing cookies manually.

To fix this manually, I removed the "access_token" cookie, and the page began functioning correctly as expected, but I would need to log back in. 

To replicate the issue, you can try removing the "refresh_token" cookie using the browser's developer tools.

**Comment by Blaumaus** [comment]
Thank you for reporting it, working on a fix
