### ISSUE TITLE
Feature request: Remember time filter

### ISSUE THREAD

**Issue by igorkulman** [Swetrix/swetrix-fe#36]
If I switch the time filter from 7 days to Today for my projects and close the website the next time I open the website and a project it is switched back to 7 days. Would be nice if it was remembered.

**Comment by Blaumaus** [comment]
Thanks, this feature will me added soon

**Comment by Blaumaus** [comment]
Implemented at https://github.com/Swetrix/swetrix-fe/commit/da31081b0f7639bef2a17a7fcb98ccedca02727c
