### ISSUE TITLE
Overview data not recalculating when switching time frame

### ISSUE THREAD

**Issue by igorkulman** [Swetrix/swetrix-fe#37]
When I switch between 7 days and Today only the labels change, the data stays the same.

![Apr-25-2022 10-47-02](https://user-images.githubusercontent.com/4746070/165092401-2670436a-7c33-4c26-9021-35473c57c17d.gif)

**Comment by igorkulman** [comment]
No HTTP 500 but I think the timestamp calculation might be wrong. I added the tracking code yesterday afternoon so maybe it thinks last 7 days and Today is the same data? Is Today really Today or now - 24h?

**Comment by Blaumaus** [comment]
I will add Today and Yesterday periods too.

Right now I am working on a setting for users timezone, but as these new periods are fixed, they will rely on this timezone setting.

It will take some time to implement it, but you can expect these improvements to be introduced this week.

**Comment by Blaumaus** [comment]
Hello @igorkulman, the requested feature have been implemented! Sorry it took a bit more than a week to do that 🙂
Also as it's a fixed period, it will work best when you specify your 'Timezone preference' in the Swetrix account settings.

Waiting for your review. Have a great day!

**Comment by igorkulman** [comment]
Looks fine, thanks you!
