### ISSUE TITLE
Chat randomly showing new unread message badge

### ISSUE THREAD

**Issue by igorkulman** [Swetrix/swetrix-fe#42]
From time to time when I open Swetrix the "Re-open chat" button shows a red badge with 1 indicating 1 unread message. The problem is there is no unread message, my last received message there is read and 2 weeks old. 

I have not found a pattern, seems just random, like say a 30% chance to see the badge when I open Swetrix.

**Comment by Blaumaus** [comment]
I'll investigate this issue.

**Comment by Blaumaus** [comment]
fixed in https://github.com/Swetrix/chat/commit/945323d6eeeced7b52d7645f695c3a3045f8e86e
