### ISSUE TITLE
Unable to clear 'Allowed origins' in project settings once set

### ISSUE THREAD

**Issue by dillonstreator** [Swetrix/swetrix-fe#434]
Once a value is set in the  'Allowed origins' field of project settings, it's unable to be reset/cleared by leaving empty. The initial field contents are retained.

![image](https://github.com/Swetrix/swetrix-fe/assets/26043866/b3c87894-ef7c-4bee-afd1-657056c5dd2f)

**Comment by Blaumaus** [comment]
Hi, thanks for reporting it. Will fix

**Comment by Blaumaus** [comment]
fixed at https://github.com/Swetrix/swetrix-api/commit/fa55905afc587a7ec45ddcdf62dd12bb98f0a8b1
thanks for reporting this again
